Update branch for cinder to the branch to test [hardcoded]

diff --git a/jenkins/jobs/dsvm-cinder-driver.yaml b/jenkins/jobs/dsvm-cinder-driver.yaml
--- a/jenkins/jobs/dsvm-cinder-driver.yaml
+++ b/jenkins/jobs/dsvm-cinder-driver.yaml
@@ -21,12 +21,7 @@
               # sudo -H pip install mydriverclient
               echo "Configure the local.conf file to properly setup hp lefthand driver in cinder.conf"
               cat <<EOF >$BASE/new/devstack/local.conf
-
            
-#           CINDER_REPO = https://review.openstack.org/openstack/cinder
-#           CINDER_BRANCH = refs/changes/56/253356/8
-
-
           [[post-config|\$CINDER_CONF]]
           [DEFAULT]
           enabled_backends=disco
@@ -67,26 +62,26 @@
  
 
               echo "Cherry-picking latest driver from gerrit"
-              cd $BASE/new/cinder
-          
-              # fetch latest patchset from gerrit
-              UPSTREAM_REMOTE=https://review.openstack.org/openstack/cinder
-          
-              # set this to your gerrit change number
-              CHANGE_NUM=253356
-          
-              PATCHSET_BASE=refs/changes/${CHANGE_NUM:(-2)}/$CHANGE_NUM
-              LATEST_PATCHSET=$(git ls-remote $UPSTREAM_REMOTE $PATCHSET_BASE/\* |
-                                sort -t/ -k 5 -n | tail -n1 | cut -d$'\t' -f2)
-          
-              if [ -z "$LATEST_PATCHSET" ]; then
-                  echo "Failed to determine latest patchset of $PATCHSET_BASE from $UPSTREAM_REMOTE"
-                  exit 1
-              fi
-          
-              echo "Latest patchset ref is $LATEST_PATCHSET"
-                        
-              git fetch $UPSTREAM_REMOTE $LATEST_PATCHSET && git cherry-pick FETCH_HEAD
+#              cd $BASE/new/cinder
+#          
+#              # fetch latest patchset from gerrit
+#              UPSTREAM_REMOTE=https://review.openstack.org/openstack/cinder
+#          
+#              # set this to your gerrit change number
+#              CHANGE_NUM=253356
+#          
+#              PATCHSET_BASE=refs/changes/${CHANGE_NUM:(-2)}/$CHANGE_NUM
+#              LATEST_PATCHSET=$(git ls-remote $UPSTREAM_REMOTE $PATCHSET_BASE/\* |
+#                                sort -t/ -k 5 -n | tail -n1 | cut -d$'\t' -f2)
+#          
+#              if [ -z "$LATEST_PATCHSET" ]; then
+#                  echo "Failed to determine latest patchset of $PATCHSET_BASE from $UPSTREAM_REMOTE"
+#                  exit 1
+#              fi
+#          
+#              echo "Latest patchset ref is $LATEST_PATCHSET"
+              git fetch https://review.openstack.org/openstack/cinder refs/changes/56/253356/8 && git cherry-pick FETCH_HEAD              
+#              git fetch $UPSTREAM_REMOTE $LATEST_PATCHSET && git cherry-pick FETCH_HEAD
 
           }}
 
